### ISSUE TITLE
What is the error please?

### ISSUE THREAD

**Issue by anhdodotnet** [TheHudek/FandomVideoGenerator#3]
I tried running the program and got this error for the first time
![image](https://user-images.githubusercontent.com/25850343/202846427-7ef511af-8ea4-48c3-9223-85d80f865277.png)

**Comment by TheHudek** [comment]
Looking at the error log your problem is with the .env file. It tries to query "$P$G" as the page title, but cannot find it in the specified fandom subdomain. Also, make sure to rename `.env.template` to `.env`. If the file extensions are hidden (for instance, you can't see `main.py`, only `main` in your windows explorer), disable hiding it in the folder options.

E.g. For [https://gameofthrones.fandom.com/wiki/Daenerys_Targaryen](https://gameofthrones.fandom.com/wiki/Daenerys_Targaryen), the code snippet should be:
```
PROMPT="Daenerys_Targaryen"
WIKI="gameofthrones"
```

**Comment by anhdodotnet** [comment]
> PROMPT="Daenerys_Targaryen"
> WIKI="gameofthrones"

I tried again and changed the file ".env.template" to ".env", but it still got the same error
![image](https://user-images.githubusercontent.com/25850343/202853448-9cc18687-1817-49b3-9ec7-d98b84837b07.png)

**Comment by TheHudek** [comment]
I've tried recreating this issue and the only way I could do it is if I specified `PROMPT="$P$G"` in the `.env` file. Could you please make sure that the `.env` file is saved? Alternatively, create a [virtual environment](https://docs.python.org/3/library/venv.html#module-venv) and see if the issue still persists. What prompt did you give to the `.env` initially? I've tested the tool in Python 3.10.4, but it should work in any python3 versions.
